### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by witchdrash** [shibbir/generator-angular2-typescript#10]
**-- Fix seems to be to force reflect-metadata to 0.1.3, the current version (0.1.4) appears to be broken. Proposed change which fixes up the solution.**

Done a simple install using webpack, gulp and foundation, run the default gulp task and get the following errors:

C:\source\temp4>gulp
(node:4736) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[11:11:11] Using gulpfile C:\source\temp4\gulpfile.js
[11:11:11] Starting 'default'...
[11:11:11] Starting 'clean:dist'...
[11:11:11] Finished 'clean:dist' after 3.1 ms
[11:11:11] Starting 'server'...
 70% 3/3 build moduleshttp://localhost:3000/
webpack result is served from http://localhost:3000/
content is served from C:\source\temp4
404s will fallback to /index.html
 44% 4/7 build modulests-loader: Using typescript@1.8.10 and C:\source\temp4\tsconfig.json
chunk    {0} app.js, app.css (app) 6.43 kB {2} [rendered]
chunk    {1} polyfills.js, polyfills.css (polyfills) 769 kB [rendered]
chunk    {2} vendor.js (vendor) 3.3 MB {1} [rendered]

WARNING in ./~/reflect-metadata/Reflect.js
Critical dependencies:
841:28-35 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/reflect-metadata/Reflect.js 841:28-35

WARNING in ./~/reflect-metadata/package.json
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\source\temp4\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.provide (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:140:24)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/README.md
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\README.md Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\source\temp4\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/Reflect.js.map
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\Reflect.js.map Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:10)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\source\temp4\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/LICENSE
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\LICENSE Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:7)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\source\temp4\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/bower.json
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\bower.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\source\temp4\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/spec/biblio.json
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\spec\biblio.json Unexpected token (2:56)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:56)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\source\temp4\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/tsconfig.json
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\tsconfig.json Unexpected token (2:19)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:19)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\source\temp4\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/test/tsconfig.json
Module parse failed: C:\source\temp4\node_modules\reflect-metadata\test\tsconfig.json Unexpected token (2:19)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:19)
    at Parser.pp$4.raise (C:\source\temp4\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\source\temp4\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\source\temp4\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\source\temp4\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\source\temp4\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\source\temp4\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\source\temp4\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\source\temp4\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\source\temp4\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\source\temp4\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\source\temp4\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/reflect-metadata.d.ts
Module build failed: Error: Typescript emitted no output for C:\source\temp4\node_modules\reflect-metadata\reflect-metadata.d.ts
    at Object.loader (C:\source\temp4\node_modules\ts-loader\index.js:456:15)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/Reflect.ts
Critical dependencies:
841:28-35 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/reflect-metadata/Reflect.ts 841:28-35

WARNING in ./~/reflect-metadata/typings.d.ts
Module build failed: Error: Typescript emitted no output for C:\source\temp4\node_modules\reflect-metadata\typings.d.ts
    at Object.loader (C:\source\temp4\node_modules\ts-loader\index.js:456:15)
 @ ./~/reflect-metadata ^.\/.*$

WARNING in ./~/reflect-metadata/typings/node.d.ts
Module build failed: Error: Typescript emitted no output for C:\source\temp4\node_modules\reflect-metadata\typings\node.d.ts
    at Object.loader (C:\source\temp4\node_modules\ts-loader\index.js:456:15)
 @ ./~/reflect-metadata ^.\/.*$

ERROR in ./~/reflect-metadata/Reflect.ts
(96,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(133,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(174,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(255,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(298,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(335,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(376,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(401,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(433,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(469,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(494,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(526,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(562,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(587,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(619,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(655,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(680,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(712,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(748,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(772,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(803,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(838,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(862,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(893,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(928,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(953,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(985,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in ./~/reflect-metadata/Reflect.ts
(1021,21): error TS2384: Overload signatures must all be ambient or non-ambient.

ERROR in C:\source\temp4\typings\globals\node\index.d.ts
(2299,5): error TS2309: An export assignment cannot be used in a module with other exported elements.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/Reflect.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/harness.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-decorate.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-definemetadata.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-deletemetadata.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-getmetadata.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-getmetadatakeys.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-getownmetadata.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-getownmetadatakeys.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-hasmetadata.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-hasownmetadata.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/reflect/reflect-metadata.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/run.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

ERROR in C:\source\temp4\tsconfig.json
error TS6059: File 'C:/source/temp4/node_modules/reflect-metadata/test/spec.ts' is not under 'rootDir' 'C:/source/temp4/src'. 'rootDir' is expected to contain all source files.

**Comment by shibbir** [comment]
Fixed with [#c3546ae](https://github.com/shibbir/generator-angular2-typescript/commit/c3546ae35fd95c1a7fd5eec19373f958fc80df9d)
